version: "2"
services:
        igui_exporter:
                image: igui_exporter:latest
                entrypoint: 'python igui_exporter.py '
                command: '--host 134.104.18.167  --port 5000 --igui-url http://134.104.16.96 --igui-user <> --igui-pass <> --igui-parent <parent_naem or id> --log-level info'
                expose:
                        - "5000"

